name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
    
jobs:
  execute-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

     
      - name: Run install
        run: |
          chmod +x ./install/install.sh
          ./install/install.sh

      - name: Run app
        run: |
          python kittyconsole.py
